# Пользователи
@hostname = http://localhost
@port = 3008
@host = {{hostname}}:{{port}}
@parentPath = favorite
@contentType = application/json
@filmId = 642b1589f2a7670b6d002995

## Добавить в избранное
POST {{host}}/{{parentPath}}/{{filmId}}/1 HTTP/1.1
###

## Убрать из избранного
POST {{host}}/{{parentPath}}/{{filmId}}/0 HTTP/1.1
Content-Type: {{contentType}}
###

## Невалидный параметр в избранном
POST {{host}}/{{parentPath}}/{{filmId}}/svsbbs HTTP/1.1
###

## Получить список избранных фильмов
GET {{host}}/{{parentPath}} HTTP/1.1
###
