openapi: 3.1.0
info:
  title: "API сервер для демо-проекта 'Что посмотреть'"
  description: |-
    * Список ресурсов и маршрутов сервера
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
tags:
  - name: films
    description: Действия с фильмами.
  - name: comments
    description: Действия с комментариями
  - name: users
    description: Действия с пользователем.

paths:
  /users/register:
    post:
      tags:
      - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя

      requestBody:
        description: Информация для создания нового пользователя.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: Пользователь с таким email уже существует.


  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение
        аватара должно быть в формате `png` или `jpg`.

  /users/login:
    post:
      tags:
      - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля

    get:
      tags:
      - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю

  /users/logout:
    delete:
      tabs:
      - users
      summary: Завершает сеанс пользователя
      description: Завершает сеанс работы - выход из закрытой части приложения

components:
  schemas:
    createUser:
      type: object

      properties:
        firstname:
          type: string
          example: Keks
        email:
          type: string
          example: keks@example.ru
        #TODO Аватар пользователя. Необязательное. Изображение пользователя в формате .jpg или .png.
        # avatarPath:
        #  type: string
        #  example: ?
        password:
          type: string
          example: 123456
    user:
      type: object

      properties:
        id:
          type: string
          example: sslj0b80s70b7s0b70s
        email:
          type: string
          example: keks@example.ru

