# Фильмы
@hostname = http://localhost
@port = 3007
@host = {{hostname}}:{{port}}
@parentPath = films
@filmId = 642b1884aef7575bbadb851a
@filmDeleteId = 642f016485ae4bf95fee04d7
@contentType = application/json

## Получить список фильмов
GET {{host}}/{{parentPath}} HTTP/1.1
###

## Создать новый фильм
POST {{host}}/{{parentPath}} HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Nemo",
  "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
  "genre": "Drama",
  "released": 2010,
  "previewVideoLink": "https://11.react.pages.academy/static/film/video/traffic.mp4",
  "videoLink": "https://11.react.pages.academy/static/film/video/bubbles.mp4",
  "starring": [
    "Bruce Willis"
  ],
  "director": "Quentin Tarantino",
  "runTime": 130,
  "posterImage": "https://11.react.pages.academy/static/film/poster/matrix.jpg",
  "backgroundImage": "https://11.react.pages.academy/static/film/background/matrix.jpg",
  "backgroundColor": "#B9B27E"
}
###

## Обновить фильм
PATCH  {{host}}/{{parentPath}}/{{filmId}} HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Matrix 3"
}
###

## Получить промо фильм
GET {{host}}/{{parentPath}}/promo HTTP/1.1
###

## Получить фильм по жанру
GET {{host}}/{{parentPath}}/genres/drama HTTP/1.1
###

## Получить фильм по id
GET {{host}}/{{parentPath}}/{{filmId}} HTTP/1.1
###

## Удалить фильм по id
DELETE  {{host}}/{{parentPath}}/{{filmDeleteId}} HTTP/1.1
###