# Фильмы
@hostname = http://localhost
@port = 3008
@host = {{hostname}}:{{port}}
@parentPath = films
@filmId = 642b1884aef7575bbadb851a
@filmDeleteId = 643040d4926ca3e9c11ebc88
@contentType = application/json
@userId = 6442c65bfafc34b1e2fa8b49
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAb3Zlcmxvb2submV0IiwiaWQiOiI2NDQyYzY1YmZhZmMzNGIxZTJmYThiNDkiLCJpYXQiOjE2ODI0NDM4ODksImV4cCI6MTY4MjYxNjY4OX0.mj0noms9c6JHAMcLXLezxgj_Yilsfy5Uz5yuyxAiVkk

## Получить список фильмов
GET {{host}}/{{parentPath}} HTTP/1.1
###

## Получить список фильмов Auth
GET {{host}}/{{parentPath}} HTTP/1.1
Authorization: Bearer {{token}}
###

## Получить список фильмов c лимитом
GET {{host}}/{{parentPath}}?limit=1 HTTP/1.1
###

## Создать новый фильм
POST {{host}}/{{parentPath}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "name": "Bob",
  "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
  "genre": "Comedy",
  "released": 2010,
  "previewVideoLink": "https://11.react.pages.academy/static/film/video/traffic.mp4",
  "videoLink": "https://11.react.pages.academy/static/film/video/bubbles.mp4",
  "starring": [
    "Bruce Willis"
  ],
  "created": "2023-04-07T15:02:21.795Z",
  "director": "Quentin Tarantino",
  "runTime": 130,
  "posterImage": "https://11.react.pages.academy/static/film/poster/matrix.jpg",
  "backgroundImage": "https://11.react.pages.academy/static/film/background/matrix.jpg",
  "backgroundColor": "#B9B27E",
  "rating": 0
}
###
###

## Загрузка изображения для картинки
@fileName = test
@fileExt = jpg
POST {{host}}/{{parentPath}}/{{filmId}}/image HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="posterImage"; filename="{{fileName}}.{{fileExt}}"
# Content-Type: image/{{fileExt}}
Content-Type: image/jpeg

< /Users/dmitrij/Documents/{{fileName}}.{{fileExt}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Обновить фильм
PATCH  {{host}}/{{parentPath}}/{{filmId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "name": "Matrix 3"
}
###

## Получить промо фильм
GET {{host}}/{{parentPath}}/promo HTTP/1.1
###

## Получить фильм по жанру
GET {{host}}/{{parentPath}}/genres/drama HTTP/1.1
###
## Получить фильм по несуществующему жанру
GET {{host}}/{{parentPath}}/genres/lalalala HTTP/1.1
###
## Получить фильм по жанру c лимитом
GET {{host}}/{{parentPath}}/genres/comedy?limit=1 HTTP/1.1
###

## Получить фильм по id
GET {{host}}/{{parentPath}}/{{filmId}} HTTP/1.1
###

## Удалить фильм по id
DELETE  {{host}}/{{parentPath}}/{{filmDeleteId}} HTTP/1.1
Authorization: Bearer {{token}}
###