# Пользователи
@hostname = http://localhost
@port = 3007
@host = {{hostname}}:{{port}}
@parentPath = comments
@contentType = application/json
@filmId = 642b1884aef7575bbadb851a

## Создать комментарий
POST {{host}}/{{parentPath}}/{{filmId}} HTTP/1.1
Content-Type: {{contentType}}

{
  "text": "Lorem ipsum",
  "rating": 5
}

###

## Получить список комментариев
GET  {{host}}/{{parentPath}} HTTP/1.1
###