# Пользователи
@hostname = http://localhost
@port = 3008
@host = {{hostname}}:{{port}}
@parentPath = users
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAb3Zlcmxvb2submV0IiwiaWQiOiI2NDQyYzY1YmZhZmMzNGIxZTJmYThiNDkiLCJpYXQiOjE2ODI0NDg4MTMsImV4cCI6MTY4MjYyMTYxM30.Xk5mqS_RX9Ukv9cI6cX4QnDznRYFswZTbFhPDGlrT-U
## Регистрация пользователя

POST {{host}}/{{parentPath}}/register HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "keks_new@overlook.net",
  "firstname": "keks",
  "lastname": "keksovich",
  "password": "shining"
}

###

## Авторизация пользователя

POST {{host}}/{{parentPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "keks@overlook.net",
  "password": "shining"
}
###

## Проверка токена пользователя
GET {{host}}/{{parentPath}}/login HTTP/1.1
Authorization: Bearer {{token}}

###
###
## Отправка аватарки пользователю

POST {{host}}/{{parentPath}}/avatar HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="man.png"
Content-Type: image/png

< /Users/dmitrij/Documents/man.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--