# Пользователи
@hostname = http://localhost
@port = 3008
@host = {{hostname}}:{{port}}
@parentPath = users
@contentType = application/json
@userId = 642b1589f2a7670b6d002993
## Регистрация пользователя

POST {{host}}/{{parentPath}}/register HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "torans@overlook.net",
  "avatarPath": "torrance.png",
  "firstname": "Jack",
  "lastname": "Torrance",
  "password": "shining"
}

###

## Авторизация пользователя

POST {{host}}/{{parentPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "torans@overlook.net",
  "password": "shining"
}
###

## Проверка токена пользователя
GET {{host}}/{{parentPath}}/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0MmIzNmVkYzE0YjZlYzVhOWRhNWI4NiIsImlhdCI6MTY4MTg0MzQwMCwiZXhwIjoxNjgyMDE2MjAwfQ.yXobVdn653PjcV0a7fULlKPusXLDk4IeVhPVWrW1tgo

###
###
## Отправка аватарки пользователю

POST {{host}}/{{parentPath}}/{{userId}}/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="man.png"
Content-Type: image/png

< /Users/dmitrij/Documents/man.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--